[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "bonsai-nn-library"
description = "Common PyTorch utilities for research projects on neural networks."
readme = "README.md"
requires-python = ">= 3.12"
version = "0.6.0"
license = { text = "MIT" }
authors = [
    { name = "Richard Lange", email = "opensource@bonsai-neuro-ai.com" },
]
classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 1 - Planning",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "jsonargparse",
    "matplotlib",
    "mlflow",
    "numpy",
    "nvidia-dali-cuda130",
    "pandas",
    "parse",
    "pycocotools",
    "pydot",
    "pyyaml",
    "scikit-learn",
    "scipy",
    "seaborn",
    "tabulate",
    "torch>=2",
    "torchmetrics",
    "torchvision",
    "tqdm",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cuda" }]
torchvision = [{ index = "pytorch-cuda" }]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu132"  # SET CUDA MAJOR.MINOR VERSION HERE
explicit = true

[project.urls]
Repository = "https://github.com/bonsai-neuro-ai/nn-library"

[tool.black]
line-length = 100
