model1:
  class_path: nn_lib.models.ResNet
  init_args:
    depth: 20
    width: 16
    num_classes: 10
model2:
  class_path: nn_lib.models.ResNet
  init_args:
    depth: 20
    width: 16
    num_classes: 10
